### ISSUE TITLE
Crash with uninitialized mouse mode pointer on Windows (and probably GNU/Linux)

### ISSUE THREAD

**Issue by retifrav** [konovalov-aleks/reSL#4]
I've built the game on Windows, and it built fine, but it crashes on launch:

``` cmd
> resl.exe
Renderer: direct3d
Supported pixel formats:
        SDL_PIXELFORMAT_ARGB8888
        SDL_PIXELFORMAT_YV12
        SDL_PIXELFORMAT_IYUV
Pixel format: SDL_PIXELFORMAT_ARGB8888

> echo %errorlevel%
-1073741819
```

Debugger says the following:

``` cmd
A breakpoint instruction (__debugbreak() statement or a similar call) was executed in resl.exe.

ucrtbased.dll!00007fffeebe2fb5()
ucrtbased.dll!00007fffeebe3153()
ucrtbased.dll!00007fffeebfae2d()
ucrtbased.dll!00007fffeec01345()
ucrtbased.dll!00007fffeec00bd7()
ucrtbased.dll!00007fffeebfebc8()
ucrtbased.dll!00007fffeec018af()
resl.exe!resl::taskMouseEventHandling() Line 81
    at reSL\src\game\mouse\mouse.cpp(81)
```

and that line is:

``` cpp
assert(mouse::g_state.mode);
```

So it looks like the problem is that this pointer is not initialized. I am unfortunately a bit stupid when it comes to C++ and pointers, so I couldn't figure out how to fix it.

I have also tried it on GNU/Linux, and there it crashes on launch too, probably for the same reason (*although I haven't attached a debugger to verify that*).

Finally, I've tried to build and run it on Mac OS, and there the game launched just fine, no crash.

**Comment by konovalov-aleks** [comment]
Hello! Thank you for report!

The crash is already fixed several days ago: https://github.com/konovalov-aleks/reSL/pull/2

Please, try to update the source and build again

**Comment by retifrav** [comment]
You are right, I was on a bit older commit, I should've specified that.
Yes, with the latest sources it doesn't crash anymore, thank you!

Also tested it on GNU/Linux (*Steam Deck, in fact*), and it works fine there too (*the initial problem turned out to be unrelated*):

![resl-steam-deck](https://github.com/user-attachments/assets/ae5a057e-3093-428f-be43-9d76cd636c1e)
