### ISSUE TITLE
The manual screens/pages are screwed on Windows

### ISSUE THREAD

**Issue by retifrav** [konovalov-aleks/reSL#6]
If one opens the Manual menu in Windows version, the pages are displayed screwed like this:

![resl-manual-screwed](https://github.com/user-attachments/assets/23137ba0-81af-4c53-8292-71faf8d7361a)

That's not the end of the world, one can always just open the original `RULES.TXT`, but still I thought this is something worth reporting.

On other platforms the Manual displays fine, all the pages can be read without problems.

**Comment by konovalov-aleks** [comment]
Windows build hasn't been tested much, thanks for sharing this report! I think it's because of the text file mode in Windows, which replaces line endings. Will fix it soon

**Comment by konovalov-aleks** [comment]
One more problem is that the original game ignores errors almost anywhere (it doesn't even check if file reading was successful; the same situation with the preparation of the manual text). My first goal was to reimplement the game as close as possible to the original code (the branch "original" is that code; I hope it will be useful for those who want to learn reverse engineering). I'll improve error handling in main branch later.

**Comment by retifrav** [comment]
Sure, there is no rush, the game already runs just fine, fantastic job, and these things (*by the way, there is one more bugreport incoming, hehe*) are just very minor inconveniences.

**Comment by retifrav** [comment]
Tried it out after the fix - now the Manual displays fine on Windows too, thank you!
