### ISSUE TITLE
The Archive menu doesn't clear its overlay screen

### ISSUE THREAD

**Issue by retifrav** [konovalov-aleks/reSL#7]
If one opens the Records menu (*there should be at least one record there for the problem to appear*), and then close it and open the Archive menu (*there should be no saved games there for the problem to appear*), then the menu "overlay" doesn't clear, so the screen doesn't draw properly, although the game still reacts to the menu keys, such as opening the Manual or something else.

After any other menu is opened, the screen clears and renders fine afterwards, until this sequence of actions is repeated again (*open Records and then Archive*).

Here's a video to demonstrate the problem:

https://github.com/user-attachments/assets/dd15eb34-f53a-4706-a9a3-9c87631eea9b

I could reproduce it on Mac OS and Windows.

**Comment by konovalov-aleks** [comment]
Thank you for report! 

Fun fact: this bug is reproducible in the original game :)) 
I know about this issue (and the same problem occurs when the user removes the last save file), will fix it later
